### ISSUE TITLE
Unstable when doing requests in parallel

### ISSUE THREAD

**Issue by mrft** [jgovaerts/sri-audit-broadcast#2]
With 5 requests in parallel, doing about 5000 PUTs results in 'connection reset'.

25 PUTs in parallel fails immediately.

For details, talk to Matthias.

**Comment by jgovaerts** [comment]
This turned out to be caused due to slow database requests in sri4node. So this is a sri4node issue, see
https://github.com/dimitrydhondt/sri4node/issues/103.
